AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "test/**/*"
    - "vendor/**/*"
    # Excluded files
    - "config/routes.rb"

# Rails
Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

# Documentation
Documentation:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Max: 64
  CountComments: false

Metrics/MethodLength:
  Max: 64

Metrics/ModuleLength:
  Max: 64
  CountComments: false

Metrics/ClassLength:
  Max: 320
  CountComments: false

Metrics/LineLength:
  Max: 320

# Style
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded
